/*
 * This Scala source file was generated by the Gradle 'init' task.
 */
package taller

object App {
  def main(args: Array[String]): Unit = {
    println(greeting())
    println(greeting2())
  }

  def greeting(): String = "Hello world!"
  def greeting2(): String = "hola, prueba"
}
